# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Programmer Blog
email: tito@pandubrahmanto.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, nama saya Tito Pandu Brahmanto.
  Saya adalah seorang Software Engineer yang bekerja di Vidio.com.
  Opini dalam blog ini mewakili opini saya dan bukan merupakan opini dari tempat saya bekerja.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tito.pandubrahmanto.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tito_pandu
github_username:  titopandub
linkedin_username: titopandub
locale: 'id_ID' 
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail:
    before: 2
    after: 2
disqus:
  shortname: blogtitopandu
google_analytics: G-FDTHZVEBX6
facebook:
  app_id: 1450324088312218
google_site_verification: "05vIbG4L6TMMz7ZRjI-6G8hCXj6yhxz02Ool0YVwmlg"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
lsi: true
